language: c
install:
- "sudo apt-get install -y devscripts"
script:
- "./scripts/build_source_package.sh"
- "./scripts/upload_source.sh"
#deploy:
#  provider: releases
#  api_key:
#    secure: oW9qKQUu3C6lzy14cU/6nnTwLAkqNZ4ki/kD8GEQiQl47Wfz/pHcRVc8ioc/KLsy3rP3NYNLk/CBU/lYNvYfOh2jiatjsCL6UhLKIgg8icD/wY9efJrnBvExDi3+WhFR9jUuZfKJqNw/a2GsajBGsRMbO/NUq76futv04emZKMM=
#  file: rust-nightly-build.tar.gz
#  skip_cleanup: true
#  on:
#    repo: ealasu/rust-armhf-builds
