#!/bin/sh

set -e

rust='rust-nightly-armhf'

case "$1" in
remove)
update-alternatives --remove rustc /usr/lib/rust/$rust/bin/rustc
;;
esac

# see postinst
rm /etc/ld.so.conf.d/${rust}.conf
ldconfig

#DEBHELPER#
